sonata_notification:
    backend: sonata.notification.backend.runtime
    #backend: sonata.notification.backend.postpone
    #backend: sonata.notification.backend.doctrine
    #backend: sonata.notification.backend.rabbitmq

    backends:
        doctrine:
            message_manager: sonata.notification.manager.message.default
            max_age:         86400     # max age in second
            pause:           500000    # delay in microseconds
            batch_size:      10        # number of messages on each iteration
            states:                    # raising errors level
                in_progress: 10
                error:       20
                open:        100
                done:        10000
    admin:
        enabled: false